REFUSAL_MESSAGE = (
    "This assistant provides publicly available facts only and does not "
    "offer investment advice. For guidance, visit: "
    "amfiindia.com/investor-corner"
)

ADVICE_PHRASES = [
    "i recommend", 
    "you should", 
    "i suggest", 
    "consider investing", 
    "better option", 
    "good choice"
]

def validate_response(response: str) -> str:
    """
    Validate the LLM response to ensure it includes a citation and leaks no advice.
    
    Args:
        response (str): The response text generated by the LLM.
        
    Returns:
        str: The original response if safe, or a fallback refusal message if a rule is violated.
    """
    # Check 1: Citation present
    # If the response does not contain a URL starting with "http", replace it.
    if "http" not in response:
        return "Please visit icicipruamc.com or amfiindia.com for details on this."
        
    # Check 2: No advice leaked
    # Scans for restricted advisory phrases (case-insensitive).
    response_lower = response.lower()
    for phrase in ADVICE_PHRASES:
        if phrase in response_lower:
            return REFUSAL_MESSAGE
            
    # If all checks pass, return the original response
    return response
